Feature/add services
h2020-pulsar/tools-ros2asn1 pull request #1
Opened 2020-08-10 15:21 UTC by cleprt

2020-08-13 15:26 UTC, vbissonnette requested changes

2020-08-13 15:26 UTC, vbissonnette commented on python/ros2asn1/RosAsn1Generator.py
> +        self.has_service = ( len(srvs) > 0)
```suggestion
        self.has_msg = (len(msgs) > 0) 
        self.has_service = (len(srvs) > 0)
```

2020-08-13 15:26 UTC, vbissonnette commented on python/ros2asn1/RosAsn1Generator.py
> +        for msg in msgs:
Is this change necessary ?

2020-08-13 15:26 UTC, vbissonnette commented on python/ros2asn1/ros2asn1.py
> +                return false
`sys.exit(-1)` exits the program entirely. I don't think `return false` is called at all.

2020-08-17 07:17 UTC, cleprt commented on python/ros2asn1/RosAsn1Generator.py
> +        for msg in msgs:
No its not, i remove it

2020-08-17 19:42 UTC, vbissonnette approved these changes

2020-08-17 19:43 UTC, merged